PRAGMA foreign_keys = ON;
PRAGMA auto_vacuum = FULL;
CREATE TABLE EMPLEADOS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE VARCHAR2(128), EMAIL VARCHAR2(128), TELEFONO VARCHAR2(128), SALARIO NUMBER);
INSERT INTO EMPLEADOS (ID,NOMBRE,EMAIL,TELEFONO,SALARIO) VALUES (1,'Santiago','SGARCIA@ALGO.COM','999999',10000.00);
INSERT INTO EMPLEADOS (ID,NOMBRE,EMAIL,TELEFONO,SALARIO) VALUES (2,'Orlando','SGARCIA@ALGO.COM','8989899',10000);
INSERT INTO EMPLEADOS (ID,NOMBRE,EMAIL,TELEFONO,SALARIO) VALUES (3,'David','SGARCIA@ALGO.COM','8989899',10000);
